packages

```{r}
library(tidyverse)
library(cmdstanr)
library(readxl)
library(posterior)
source("functions.R")
```

```{r}
workbook <- "scores.xlsx"
# sheet <- "super-league"
# sheet <- "championship"
sheet <- "league-1"
scores <- read_scores(workbook, sheet)
scores
```


```{r}
lookup <- make_lookup_table(scores)
lookup
```

convert team names to numbers

```{r}
scores %>% 
  left_join(lookup, by = c("t1"="team")) %>% 
  left_join(lookup, by = c("t2"="team")) %>% 
  select(t1 = id.x, t2 = id.y, s1, s2) -> scores_stan
scores_stan
```

make stan dataset

```{r}
scores_stan
```

compile model

```{r}
rl.1 <- cmdstan_model("poisson.stan")
rl.1
write_rds(rl.1, "rl_model.rds")
```

make data

```{r}
# scores_stan
stan_data <- list(
  ng = nrow(scores_stan),
  nt = with(scores_stan, max(t1, t2)),
  t1 = scores_stan$t1,
  t2 = scores_stan$t2,
  s1 = scores_stan$s1,
  s2 = scores_stan$s2
)
stan_data
```

run model

```{r}
fit <- rl.1$sample(data = stan_data)
```

```{r}
rat_name <- str_c(sheet, " ratings")
fit$summary() %>% 
  select(variable, mean) %>% 
  mutate(id = parse_number(variable)) %>% 
  left_join(lookup) %>% 
  select(team, mean, variable) %>% 
  mutate(mean = exp(mean)) %>% 
  arrange(desc(mean)) %>% 
  View(rat_name)
  
```

read fixtures

```{r}
fixtures <- read_fixtures(workbook, sheet, lookup)
fixtures
```

draws (from posterior)

```{r}
ll <- get_draws(fit)
draws <- ll$draws
draws_with_team <- ll$draws_with_team
```


```{r}
ppd <- make_ppd(draws, draws_with_team, 9, 1)
ppd
```

```{r}
ppd_stats(ppd)
```


```{r}
pred_name <- str_c(sheet, " preds")
fixtures %>% 
  rowwise() %>% 
  mutate(ppd = list(make_ppd(draws, draws_with_team, id.x, id.y))) %>% 
  mutate(stats = list(ppd_stats(ppd))) %>% 
  unnest_wider(stats) %>% 
  unnest_wider(prob) %>% 
  unnest_wider(means) %>% 
  round_score() %>% 
  select(t1, t2, `1`, `2`, X, s1, s2) %>% 
  View(pred_name)
```




